name: Send Email on Push

on: [push]

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Send Email
      run: |
        curl -s --user "$MAILJET_API_KEY:$MAILJET_SECRET_KEY" \
          https://api.mailjet.com/v3.1/send \
          -H 'Content-Type: application/json' \
          -d @- << EOF
          {
            "Messages": [
              {
                "From": {
                  "Email": "bhalamish20@gmail.com",
                  "Name": "Your Name"
                },
                "To": [
                  {
                    "Email": "bhalamish20@gmail.com",
                    "Name": "Recipient"
                  }
                ],
                "Subject": "GitHub Action Notification - A new commit was pushed by ${GITHUB_ACTOR}",
                "TextPart": "A new commit was pushed by ${GITHUB_ACTOR}.\nCommit repo: ${GITHUB_REPOSITORY}.\nCommit hash: ${GITHUB_SHA}.\nCheck the repository for more details.",
                "HTMLPart": "<h3>A new commit was pushed by ${GITHUB_ACTOR}.</h3><p>Commit repo: ${GITHUB_REPOSITORY}</p><p>Commit hash: ${GITHUB_SHA}</p><p>Check the repository for more details.</p>"
              }
            ]
          }
          EOF
      env:
        MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
        MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}

